version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_USER: user_db
      POSTGRES_DB: product_ordering_service_db

    ports:
    - 5433:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8078:8080